FIT5120_WasteGuardian/Controllers/BinsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FIT5120_WasteGuardian.Controllers
{
    [Authorize]
    public class BinsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Recycling()
        {
            return View();
        }

        public IActionResult Landfill()
        {
            return View();
        }

        public IActionResult Organic()
        {
            return View();
        }
    }
}

FIT5120_WasteGuardian/Controllers/DIYController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FIT5120_WasteGuardian.Controllers
{
    [Authorize]
    public class DIYController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Clothes()
        {
            return View();
        }

        public IActionResult Plastic()
        {
            return View();
        }

        public IActionResult Glass()
        {
            return View();
        }
    }
}

FIT5120_WasteGuardian/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using FIT5120_WasteGuardian.Models;
using Microsoft.AspNetCore.Authorization;
using FIT5120_WasteGuardian.Data;

namespace FIT5120_WasteGuardian.Controllers;

[Authorize] // Display website only to authorized users
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }
    
    public IActionResult Index()
    {
            return View();
    }

    public IActionResult Game()
    {
        return View();
    }

    public IActionResult SortInformation()
    {
        return View();
    }

    public IActionResult Reduce()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

FIT5120_WasteGuardian/Views/Home/Game.cshtml
@{
    ViewData["Title"] = "Test Your Knowledge";
}

<head>
    <style>
        canvas {
            border: 1px solid rgb(255, 255, 255);
        }

        .btn-primary {
            color: #212529;
            background-color: #0bd784;
            border-color: #09a666
        }

            .btn-primary:hover {
                color: #212529;
                background-color: #078e57;
                border-color: #09a666
            }

            .btn-primary:focus,
            .btn-primary.focus {
                box-shadow: 0 0 0 .2rem rgba(91, 194, 194, 0.5)
            }
    </style>
    
</head>
<body>
<div class="text-center">
    <h1 class="display-4">Where does the rubbish go?</h1>
    <p>(Drag the waste into the appropiate bins)</p>
</div>

<!-- Renders the Canvas game and imports the game Script File-->
<div style="text-align:center;">
    <audio id="pickup-sound" src="~/assets/pickup.mp3"></audio>
    <audio id="bin-sound" src="~/assets/drop.mp3"></audio>
    <canvas id="canvas" width="800" height="400"></canvas>
</div>

<!-- Section to display total score -->
<div class="row justify-content-center">
    <h2 class="text-center" id="scoreDisplay"></h2>
</div>

<!-- Designate an area to show the scores of the player -->
<div class="row justify-content-center">
    <div class="col-4 text-center">
        <span id="bin1-score"></span>
    </div>
    <div class="col-4 text-center">
        <span id="bin2-score"></span>
    </div>
    <div class="col-4 text-center">
        <span id="bin3-score"></span>
    </div>
</div>

<div class="row justify-content-center" >
        <div class="col-8 text-center" id="nextPage" style="margin-top: 1em; display: none;">
        <input type="button" class="w-100 btn btn-lg btn-primary" value="Learn how to sort your rubbish properly here." onclick="location.href='@Url.Action("SortInformation", "Home")'" />
    </div>
</div>

    <script src='~/js/game.js'></script>
</body>

FIT5120_WasteGuardian/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<head>
    <style>
        .btn-primary {
            color: #212529;
            background-color: #0bd784;
            border-color: #09a666
        }

            .btn-primary:hover {
                color: #212529;
                background-color: #078e57;
                border-color: #09a666
            }

            .btn-primary:focus,
            .btn-primary.focus {
                box-shadow: 0 0 0 .2rem rgba(91, 194, 194, 0.5)
            }
    </style>
</head>

<h1></h1>

<div class="row justify-content-center">
    <div class="col-5 text-left">
        <h1 class="display-4" style="margin-top: 2em">Welcome Waste Guardians!</h1>
        <br />
        <h4>How much do you know about trash sorting? Do you want to play a game?</h4>
        <br />
        <input type="button" class="w-100 btn btn-lg btn-primary" style="margin-top: 1em" value="Start Playing ->" onclick="location.href='@Url.Action("Game", "Home")'" />
    </div>

    <div class="col-7 text-center ">
        <img src="~/images/splashpage.png" alt="info" style="width:80%;height:80%;margin:auto;display:block; margin-top: 1em;">
    </div>
</div>


 

FIT5120_WasteGuardian/Views/Home/Reduce.cshtml
@{
    ViewData["Title"] = "Reduce Waste";
}



<div class="row justify-content-center">
    <div class="col-10 text-center">
        <h1 class="display-4" style="margin-bottom: 2em;">How to reduce waste?</h1>
    </div>
</div>

<div class="row justify-content-center">
    <div class="col-6 justify-content-start">
        <h2>Recycle</h2>
        <h5>what can be produced from recycle?</h5>
        <p>Hover over the product to see what things can be made by recycling  </p>
        
        <ul id="myList" class="list-unstyled" style="list-style-type: disc">
            <li>Plastic</li>
            <li>Paper</li>
            <li>Glass</li>
            <li>Metal</li>
        </ul>
    </div>


    <div class="col-6 justify-content-end">
        <h2>Reuse</h2>
        <h5>How can you DIY?</h5>
        <p>
            <ul>
                <li><a asp-area="" asp-controller="DIY" asp-action="Plastic">Plastic Bottles</a></li>
                <li><a asp-area="" asp-controller="DIY" asp-action="Glass">Glass</a></li>
                <li><a asp-area="" asp-controller="DIY" asp-action="Clothes">Clothes</a></li>
            </ul>
        </p>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">

    $(document).ready(function () {
        $('#myList li').each(function (index) {
            if(index == 0) {
                    var tooltipText = "Recycled Mats and Rugs\nNatural and Recycled Shoes\nRecycled Yoga Mats\nRecycled Swimwear\nRecycled Stockings\nRecycled Blankets\nRecycled Furniture\nRecycled Surfboard Fins"          
            }
            else if(index == 1) {
                    var tooltipText = "Packaging\nToilet paper\nEgg cartons\nRecycled cardboard\nInsulation\nkitty litter\nBuilding products"
            }
            else if(index == 2) {
                    var tooltipText = "New bottles\nJars\nComposite Glass Countertops\nBeads\nConstruction equipment"
            }
            else if(index == 3) {
                    var tooltipText = "Automobiles\nComputers\nBicycles\nPiping\nBridges\nEyeglass frames\nCooking pots & pans\nVarious tools"     
            }
            else {
                var tooltipText = "This is tooltip for Item " + (index + 1);
            }
            $(this).attr('title', tooltipText);
        });
    });
    </script>
}

FIT5120_WasteGuardian/Views/Home/SortInformation.cshtml
@{
    ViewData["Title"] = "Waste Sorting Information";
}

<head>
    <style>
        .btn-primary {
            color: #212529;
            background-color: #0bd784;
            border-color: #09a666
        }

            .btn-primary:hover {
                color: #212529;
                background-color: #078e57;
                border-color: #09a666
            }

            .btn-primary:focus,
            .btn-primary.focus {
                box-shadow: 0 0 0 .2rem rgba(91, 194, 194, 0.5)
            }
    </style>
</head>

<div class="row justify-content-center">
    <div class="col-6 text-center">
        <h1 class="display-4">Waste Sorting Information</h1>
    </div>
</div>

<div class="row justify-content-center">
    <div class="col-4">
        <a asp-area="" asp-controller="Bins" asp-action="Landfill">
            <img src="~/images/redBin.png" alt="Landfill" style="width:60%;height:70%;margin:auto;display:block;">
        </a>
    </div>
    <div class="col-4 justify-content-center">
        <a asp-area="" asp-controller="Bins" asp-action="Organic">
            <img src="~/images/greenBin.png" alt="Organics" style="width:60%;height:70%;margin:auto;display:block;">
        </a>
    </div>
    <div class="col-4 justify-content-center">
        <a asp-area="" asp-controller="Bins" asp-action="Recycling">
            <img src="~/images/yellowBin.png" alt="Recycling" style="width:60%;height:70%;margin:auto;display:block;">
        </a>
    </div>
</div>

<!-- This section handles the link to the next page, uses row, col classes -->
<div class="row justify-content-center">
    <div class="col-12">
        <h2 class="text-center">Click on each bin to see the correct trash sorting method for the Bin.</h2>
    </div>
</div>